<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SF6_Training_Mode_Plus</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="REFramework.NET">
      <HintPath>libs\REFramework.NET.dll</HintPath>
    </Reference>

    <Reference Include="REFrameworkDependencies">
      <HintPath>libs\generated\*.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
